project:
  type: website
  output-dir: docs

website:
  title: "Dr. Trevor Norton"
  navbar:
    left:
      - href: index.qmd
      - papers.qmd
      - teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



